require 'plugins/auto_voice'
require 'plugins/build'
require 'plugins/google'
require 'plugins/help'
require 'plugins/jenkins'
require 'plugins/msfinfo'
require 'plugins/msf_pro'
require 'plugins/msf'
require 'plugins/network'
require 'plugins/nexpose'
require 'plugins/system'
require 'plugins/urban_dictionary'
require 'plugins/vm_control'

